import Image from "next/image";
import Link from "next/link";
import Reveal from "@/components/Reveal";
import VideoFeature from "@/components/VideoFeature";
import ImageGallery from "@/components/ImageGallery";
import SectorTicker from "@/components/SectorTicker";
import {event,marketStats,sectors,media} from "@/data/site";

export default function Home(){return <>
<section className="hero"><Image src="/assets/hero-interior.webp" fill priority alt="Contemporary interior design" className="cover heroImage"/><div className="shade heavy"/><div className="heroPattern"/><div className="heroContent"><Reveal><span className="eyebrow">{event.dates} · Baghdad</span><h1>Iraq’s home & interiors market <em>meets here.</em></h1><p>An international exhibition connecting manufacturers, brands and professional buyers across Iraq’s evolving home market.</p><div className="actions"><Link className="button gold" href="/register#visitor">Visit the Expo <span>↗</span></Link><Link className="button ghost" href="/exhibit">Exhibit with Us <span>↗</span></Link></div></Reveal></div><div className="heroMeta"><span>{event.venue}</span><span>{event.city}</span><span>{event.hours}</span></div><div className="scrollCue"><span>Scroll to discover</span><i/></div></section>
<section className="institutional"><span>Organized by</span><Image src="/assets/success-steps-logo.webp" width={170} height={70} alt="Success Steps"/><span>With institutional partners</span><Image src="/assets/ministry-trade-logo.webp" width={100} height={70} alt="Ministry of Trade"/><Image src="/assets/expo-partner-logo.webp" width={110} height={70} alt="Partner"/></section>
<SectorTicker/>
<section className="splitIntro"><Reveal><span className="eyebrow dark">About the Exhibition</span><h2>Where design, products and business opportunity come together.</h2></Reveal><Reveal><p>Iraq Home Expo creates a focused meeting point for companies serving the home, interiors and residential markets—connecting international supply with professional demand in Iraq.</p><Link href="/about" className="textLink">Discover Iraq Home Expo <span>↗</span></Link></Reveal></section>
<section className="sectorShowcase"><div className="sectionHead"><span className="eyebrow">Eight Core Industries</span><h2>Explore the exhibition sectors.</h2><Link href="/sectors" className="textLink light">View all sectors ↗</Link></div><div className="sectorRail">{sectors.map((s,i)=><Link href={`/sectors/${s.slug}`} className="sectorCard" key={s.slug}><Image src={s.image} fill alt={s.title}/><div className="cardShade"/><span className="index">0{i+1}</span><div><h3>{s.title}</h3><p>{s.short}</p><span>Explore ↗</span></div></Link>)}</div></section>
<ImageGallery/>
<section className="market"><div className="marketIntro"><span className="eyebrow dark">Why Iraq</span><h2>A market in motion.</h2><p>Urban growth, residential development and demand for improved living standards are creating opportunities across Iraq’s home and residential sectors.</p><Link className="button dark" href="/why-iraq">Discover Why Iraq <span>↗</span></Link></div><div className="statsGrid">{marketStats.map(([n,l,d])=><Reveal key={l} className="stat"><strong>{n}</strong><span>{l}</span><small>{d}</small></Reveal>)}</div></section>
<section className="storyCards"><Link href="/visit" className="storyCard"><Image fill src="/assets/industry-professionals.webp" alt="Industry professionals"/><div className="cardShade"/><div><span>Visit</span><h2>Meet buyers & industry professionals.</h2><p>Discover products, suppliers and new business connections in Baghdad.</p><b>Plan your visit ↗</b></div></Link><Link href="/exhibit" className="storyCard"><Image fill src="/assets/build-partnerships.webp" alt="Business partnership"/><div className="cardShade"/><div><span>Exhibit</span><h2>Build partnerships in Iraq.</h2><p>Present your company to professionals actively sourcing products and solutions.</p><b>Exhibit with us ↗</b></div></Link></section>
<VideoFeature title="Experience the work behind the exhibition" copy="Watch organizer achievements and previous exhibition work. This panel currently links to the Success Steps YouTube channel and is ready for a specific showreel embed when you provide it." channelUrl={media.organizerYoutube}/>
<section className="finalCta"><div><span className="eyebrow">Be part of Iraq Home Expo 2027</span><h2>Meet the market in Baghdad.</h2></div><div><p>{event.dates}<br/>{event.venue}<br/>{event.city}</p><Link className="button gold" href="/register">Register Now <span>↗</span></Link></div></section>
</>}
