import PageHero from "@/components/PageHero";
import VisualBand from "@/components/VisualBand";
import VideoFeature from "@/components/VideoFeature";
import Link from "next/link";
import {marketStats,sectors,event,media} from "@/data/site";
export const metadata={title:"Exhibit at Iraq Home Expo"};
export default function Exhibit(){return <><PageHero eyebrow={`${event.dates} · Baghdad`} title="Exhibit at Iraq Home Expo 2027" copy="Present your products, meet professional buyers and build commercial relationships in Iraq’s developing home and residential market." image="/assets/build-partnerships.webp" primary="Register as an Exhibitor" primaryHref="/register#exhibitor"/>
<section className="featureGrid six">{[["Access the Iraqi market","Introduce your products to professionals across Iraq’s home sectors."],["Meet professional buyers","Connect with importers, wholesalers, retailers and purchasing specialists."],["Find distributors & partners","Meet potential distributors, agents and commercial partners."],["Showcase your products","Present collections, technologies and solutions directly to the market."],["Build brand visibility","Strengthen your company’s presence among buyers and decision-makers."],["Create new business","Generate leads and develop relationships beyond the exhibition."]].map(([h,p])=><div className="feature" key={h}><h3>{h}</h3><p>{p}</p></div>)}</section>
<section className="market compact"><div className="marketIntro"><span className="eyebrow dark">Why Iraq</span><h2>A growing market for modern home solutions.</h2><p>Use the exhibition as a focused route into market conversations, supplier relationships and commercial opportunities.</p><Link className="textLink" href="/why-iraq">Discover Why Iraq ↗</Link></div><div className="statsGrid">{marketStats.slice(0,5).map(([n,l,d])=><div className="stat" key={l}><strong>{n}</strong><span>{l}</span><small>{d}</small></div>)}</div></section>
<VisualBand image="/assets/industry-professionals.webp" eyebrow="Your target market" title="Connect with professional visitors." copy="Meet people involved in importing, sourcing, specifying, purchasing, retailing and distributing products for the Iraqi market." href="/register#exhibitor" label="Start Exhibitor Registration"/>
<section className="journeySection"><div><span className="eyebrow dark">From interest to exhibition</span><h2>Your participation journey.</h2></div><div className="journeyGrid">{[["01","Register your interest","Tell our team about your company, products and participation requirements."],["02","Speak with our sales team","Our team will contact you regarding participation and available options."],["03","Prepare your participation","Coordinate your requirements and prepare the products you want to present."],["04","Meet the market in Baghdad","Join professional visitors and industry stakeholders at Iraq Home Expo 2027."]].map(([n,h,p])=><div key={n}><span>{n}</span><h3>{h}</h3><p>{p}</p></div>)}</div></section>
<section className="sectorChips">{sectors.map(s=><Link key={s.slug} href={`/sectors/${s.slug}`}>{s.title}<span>↗</span></Link>)}</section>
<VideoFeature title="See the organizer’s exhibition work" copy="Previous projects and exhibition achievements help prospective exhibitors understand the organizer experience behind Iraq Home Expo. This placeholder opens the Success Steps YouTube channel until the final project video is selected." channelUrl={media.organizerYoutube}/>
<section className="finalCta"><div><span className="eyebrow">Be part of Iraq Home Expo 2027</span><h2>Ready to exhibit?</h2><p>Submit your company details and participation interest. Our sales team will contact you regarding next steps.</p></div><Link className="button gold" href="/register#exhibitor">Register as an Exhibitor ↗</Link></section></>}
